export const STATUS_COLORS = {
  pending:             { bg: 'bg-warning/10', text: 'text-warning', border: 'border-warning/20' },
  pending_payment:     { bg: 'bg-warning/10', text: 'text-warning', border: 'border-warning/20' },
  paid:                { bg: 'bg-success/10', text: 'text-success', border: 'border-success/20' },
  in_transit:          { bg: 'bg-info/10',    text: 'text-info',    border: 'border-info/20' },
  arrived:             { bg: 'bg-info/10',    text: 'text-info',    border: 'border-info/20' },
  out_for_delivery:    { bg: 'bg-success/10', text: 'text-success', border: 'border-success/20' },
  on_way_to_delivery:  { bg: 'bg-success/10', text: 'text-success', border: 'border-success/20' },
  done:                { bg: 'bg-success/15', text: 'text-success', border: 'border-success/25' },
  cancelled:           { bg: 'bg-error/10',   text: 'text-error',   border: 'border-error/20' },
  achete:              { bg: 'bg-info/10',    text: 'text-info',    border: 'border-info/20' },
  en_transit:          { bg: 'bg-info/10',    text: 'text-info',    border: 'border-info/20' },
  en_douane:           { bg: 'bg-warning/10', text: 'text-warning', border: 'border-warning/20' },
  disponible:          { bg: 'bg-success/10', text: 'text-success', border: 'border-success/20' },
  livre:               { bg: 'bg-success/15', text: 'text-success', border: 'border-success/25' },
  incident:            { bg: 'bg-error/10',   text: 'text-error',   border: 'border-error/20' },
} as const;

export const ORDER_STATUSES = {
  pending:             { label: "En attente",          color: "warning", icon: "clock" },
  pending_payment:     { label: "Paiement en attente", color: "warning", icon: "credit-card" },
  paid:                { label: "Payé",                color: "success", icon: "check-circle" },
  in_transit:          { label: "En transit",          color: "info",    icon: "truck" },
  arrived:             { label: "Arrivé",              color: "info",    icon: "map-pin" },
  out_for_delivery:    { label: "En livraison",        color: "success", icon: "navigation" },
  on_way_to_delivery:  { label: "Chez le livreur",     color: "success", icon: "package" },
  done:                { label: "Terminé",             color: "success", icon: "check-circle" },
  cancelled:           { label: "Annulé",              color: "error",   icon: "x-octagon" },
  achete:              { label: "Acheté",              color: "info",    icon: "shopping-bag" },
  en_transit:          { label: "En transit",          color: "info",    icon: "truck" },
  en_douane:           { label: "En douane",           color: "warning", icon: "shield" },
  disponible:          { label: "Disponible",          color: "success", icon: "package" },
  livre:               { label: "Livré",               color: "success", icon: "check-circle" },
  incident:            { label: "Incident",            color: "error",   icon: "alert-triangle" },
} as const;
